//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window.Wpf.ShipTrainingPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShipTrainingPlanner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipTrainingPlanner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.Wpf.ShipTrainingPlanner.ShipTrainingPlanner", typeof(ShipTrainingPlanner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Add ship).
        /// </summary>
        internal static string AddShip {
            get {
                return ResourceManager.GetString("AddShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (ASW Bonus).
        /// </summary>
        internal static string ASWBonus {
            get {
                return ResourceManager.GetString("ASWBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Current).
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (HP bonus).
        /// </summary>
        internal static string HPBonus {
            get {
                return ResourceManager.GetString("HPBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Level).
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Remove plan).
        /// </summary>
        internal static string RemovePlan {
            get {
                return ResourceManager.GetString("RemovePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Ship training plans).
        /// </summary>
        internal static string ViewerTitle {
            get {
                return ResourceManager.GetString("ViewerTitle", resourceCulture);
            }
        }
    }
}
